site_name: modified Entwickler Dokumentation
site_description: Einstieg in die Modulentwicklung für modified Shops
site_author: "Robin Wieschendorf, Jay Trees"
site_url: "https://docs.module-loader.de"

nav:
  - Vorwort: index.md
  - Einleitung: introduction.md
  - Die Architektur von modified: architecture.md
  - Was ist ein Modul im modified Kontext?: module-modified.md
  - Das Autoinclude System von modified: auto-include-system.md
  - System Modul: module-system.md
  - Shipping Modul: module-shipping.md
  - Payment Modul: module-payment.md
  - Appendix:
      - modifed Menüpunkte: modified-menu.md

theme:
  name: material
  language: de
  custom_dir: overrides

  features:
    #- navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.footer
    - navigation.top
    - content.action.edit
    - content.code.copy

extra_css:
  - stylesheets/extra.css

repo_url: "https://github.com/RobinTheHood/docs.module-loader.de"
repo_name: RobinTheHood/docs.module-loader.de

edit_uri: edit/main/docs/
plugins:
  - search:
      lang: de

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
