site_name: modified Entwickler Dokumentation
site_description: Einstieg in die Modulentwicklung für modified Shops
site_author: "Robin Wieschendorf, Jay Trees"
site_url: "https://docs.module-loader.de"

nav:
  - Vorwort: index.md
  - Einleitung: introduction.md
  - Die Architektur von modified: architecture.md
  - Was ist ein Modul im modified Kontext?: module-modified.md
  - Das Autoinclude System von modified: auto-include-system.md
  - System Modul: module-system.md
  - Shipping Modul: module-shipping.md
  - Payment Modul: module-payment.md
  - Appendix:
    - modifed Menüpunkte: modified-menu.md

theme:
  name: material
  language: de
  custom_dir: overrides

  features:
    #- navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.footer
    - navigation.top
    - content.action.edit
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      primary: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

repo_url: "https://github.com/RobinTheHood/docs.module-loader.de"
repo_name: RobinTheHood/docs.module-loader.de

edit_uri: edit/main/docs/

plugins:
  - search:
      lang: de

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

extra:
  generator: false
